name: wampy

version: 1.0.0

description: |
  Wamp CLI tool to make WAMP RPCs and PubSub. Useful for developing WAMP Components and their testing.


dependencies:
  saslprep: ^1.0.1
  pointycastle: ^3.3.5
  pinenacl: ^0.3.3
  logging: ^1.0.0
  pedantic: ^1.11.1
  meta: ^1.1.8
  msgpack_dart: ^1.0.0
  connectanum: ^2.0.1
  args: ^2.3.0
  dotenv: ^3.0.0
  postgres: ^2.4.3


dev_dependencies:
  test: ^1.19.2
  stream_channel: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
